#### 一个张量

In [1]:
import numpy as np
np.random.randn(2,3)

array([[-2.32948251,  0.29557121, -0.15746743],
       [ 1.24517783, -0.24812429, -1.37862929]])

#### Tensorflow 运算——张量

In [2]:
import tensorflow as tf

In [3]:
a = tf.constant(1.0)
b = tf.constant(3.0)
c = a+b

In [4]:
print(c)

tf.Tensor(4.0, shape=(), dtype=float32)


In [5]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [11]:
c = tf.constant([[4.0,5.0],[10.0,1.0]])

In [7]:
print(tf.reduce_max(c))

tf.Tensor(10.0, shape=(), dtype=float32)


In [8]:
print(tf.argmax(c))

tf.Tensor([1 0], shape=(2,), dtype=int64)


In [9]:
print(tf.nn.softmax(c))

tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


#### Tensorflow运算——变量

In [13]:
my_variable = tf.Variable(c)
print("\nIndex of highest value:",tf.argmax(my_variable))


Index of highest value: tf.Tensor([1 0], shape=(2,), dtype=int64)


#### Tensorflow运算——微分

In [16]:
import math

In [18]:
x = tf.constant(1.0)
with tf.GradientTape(persistent=True) as t:
    t.watch(x)
    y = x*x + math.exp(x)
dy_dx = t.gradient(y,x)
del t

In [19]:
dy_dx

<tf.Tensor: id=45, shape=(), dtype=float32, numpy=2.0>